pipeline_config_id: runner_config
data:
  e_commerce:
    data_format: json
    train_dir: dataset/e_commerce_train.json
    valid_dir: dataset/e_commerce_train.json
    test_dir: dataset/e_commerce_test.json
    data_specs:
      num_event_types: 5
      pad_token_id: 5
      padding_side: right
      truncation_side: right
  retweet:
    data_format: json
    train_dir: easytpp/retweet
    valid_dir: easytpp/retweet
    test_dir: easytpp/retweet
    data_specs:
      num_event_types: 3
      pad_token_id: 3
      padding_side: right
      truncation_side: right
  taxi:
    data_format: json
    train_dir: easytpp/taxi
    valid_dir: easytpp/taxi
    test_dir: easytpp/taxi
    data_specs:
      num_event_types: 10
      pad_token_id: 10
      padding_side: right
      truncation_side: right
  taobao:
    data_format: json
    train_dir: easytpp/taobao
    valid_dir: easytpp/taobao
    test_dir: easytpp/taobao
    data_specs:
      num_event_types: 20
      pad_token_id: 20
      padding_side: right
      truncation_side: right
  stackoverflow:
    data_format: json
    train_dir: easytpp/stackoverflow
    valid_dir: easytpp/stackoverflow
    test_dir: easytpp/stackoverflow
    data_specs:
      num_event_types: 22
      pad_token_id: 22
      padding_side: right
      truncation_side: right
  amazon:
    data_format: json
    train_dir: easytpp/amazon
    valid_dir: easytpp/amazon
    test_dir: easytpp/amazon
    data_specs:
      num_event_types: 16
      pad_token_id: 16
      padding_side: right
      truncation_side: right
IntensityFree_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: e_commerce
    runner_id: std_tpp
    model_id: IntensityFree
    base_dir: ./checkpoints/
  trainer_config:
    batch_size: 256
    max_epoch: 500
    shuffle: false
    optimizer: adam
    learning_rate: 0.001
    valid_freq: 1
    use_tfb: false
    metrics:
    - acc
    - rmse
    - mae
    - type_error_rate
    seed: 2019
    gpu: 0
  model_config:
    hidden_size: 32
    time_emb_size: 16
    num_layers: 2
    num_heads: 2
    mc_num_sample_per_step: 20
    sharing_param_layer: false
    loss_integral_num_sample_per_step: 20
    dropout: 0.0
    use_ln: false
    model_specs:
      num_mix_components: 3
    thinning:
      num_seq: 10
      num_sample: 1
      num_exp: 500
      look_ahead_time: 10
      patience_counter: 5
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
