pipeline_config_id: runner_config
data:
  taxi:
    data_format: json
    train_dir: easytpp/taxi
    valid_dir: easytpp/taxi
    test_dir: easytpp/taxi
    data_specs:
      num_event_types: 10
      pad_token_id: 10
      padding_side: right
  conttime:
    data_format: pkl
    train_dir: ../data/conttime/train.pkl
    valid_dir: ../data/conttime/dev.pkl
    test_dir: ../data/conttime/test.pkl
    data_specs:
      num_event_types: 5
      pad_token_id: 5
      padding_side: right
      truncation_side: right
  hawkes_1d:
    data_format: pkl
    train_dir: ../data/hawkes/train.pkl
    valid_dir: ../data/hawkes/dev.pkl
    test_dir: ../data/hawkes/test.pkl
    data_specs:
      num_event_types: 1
      pad_token_id: 1
      padding_side: right
      truncation_side: right
  retweet:
    data_format: json
    train_dir: easytpp/retweet
    valid_dir: easytpp/retweet
    test_dir: easytpp/retweet
    data_specs:
      num_event_types: 3
      pad_token_id: 3
      padding_side: right
      truncation_side: right
  taobao:
    data_format: json
    train_dir: easytpp/taobao
    valid_dir: easytpp/taobao
    test_dir: easytpp/taobao
    data_specs:
      num_event_types: 20
      pad_token_id: 20
      padding_side: right
      truncation_side: right
  stackoverflow:
    data_format: json
    train_dir: easytpp/stackoverflow
    valid_dir: easytpp/stackoverflow
    test_dir: easytpp/stackoverflow
    data_specs:
      num_event_types: 22
      pad_token_id: 22
      padding_side: right
      truncation_side: right
  amazon:
    data_format: json
    train_dir: easytpp/amazon
    valid_dir: easytpp/amazon
    test_dir: easytpp/amazon
    data_specs:
      num_event_types: 16
      pad_token_id: 16
      padding_side: right
      truncation_side: right
AttNHP_train:
  base_config:
    stage: train
    backend: torch
    dataset_id: stackoverflow
    runner_id: std_tpp
    model_id: AttNHP
    base_dir: ./checkpoints/
  trainer_config:
    batch_size: 256
    max_epoch: 500
    shuffle: false
    optimizer: adam
    learning_rate: 0.001
    valid_freq: 1
    use_tfb: false
    metrics:
    - acc
    - rmse
    seed: 2019
    gpu: -1
  model_config:
    hidden_size: 16
    time_emb_size: 4
    num_layers: 2
    num_heads: 2
    loss_integral_num_sample_per_step: 10
    use_ln: false
    thinning:
      num_seq: 2
      num_sample: 1
      num_exp: 50
      look_ahead_time: 10
      patience_counter: 5
      over_sample_rate: 5
      num_samples_boundary: 5
      dtime_max: 5
      num_step_gen: 1
